### ISSUE TITLE
About the source code.

### ISSUE THREAD

**Issue by KkCabin** [tiev-tongji/LOG-LIO#1]
Hello, thank you for your outstanding work :)
I wonder if the code will be open source and what is the approximate time?

**Comment by KkCabin** [comment]
> Hello, thank you for your outstanding work :) I wonder if the code will be open source and what is the approximate time?

Sorry, I used my mobile phone to visit your project, but the readme was not displayed at first. Thank you again for your work, and wish your paper an early acceptance.

**Comment by johnzjq** [comment]
Hi Wangchao,

The code will be made open source upon acceptance of our paper.

赵君峤
