### ISSUE TITLE
When to release the code

### ISSUE THREAD

**Issue by qian5683** [tiev-tongji/LOG-LIO#2]
Thank you for your outstanding work. May I know about when the code will be released

**Comment by h-k8888** [comment]
@qian5683  
Thanks, we will open the source code upon acceptance of our paper.

**Comment by KkCabin** [comment]
Thank you for your excellent work. After reading the paper, I am eager to give it a try. Is it convenient to know when you plan to open the source code?

**Comment by h-k8888** [comment]
@KkCabin
 We plan to open the source code next mouth, and sorry for the late reply.

**Comment by KkCabin** [comment]
@h-k8888 
Thank you!

**Comment by KkCabin** [comment]
Looking forward to your open source!

**Comment by h-k8888** [comment]
Our code is under refactoring. 
And our code will be released along with our recent work LOG-LIO2 in a few days.

**Comment by h-k8888** [comment]
Thanks for the interest in our work, the code is open-source.
And our recent work LOG-LIO2 is coming soon!
