### ISSUE TITLE
Updates on code release

### ISSUE THREAD

**Issue by chowkamlee81** [tiev-tongji/LOG-LIO#3]
Updates on code release

**Comment by h-k8888** [comment]
We plan to open the source code next mouth, and sorry for the late reply.

**Comment by chengwei0427** [comment]
> We plan to open the source code next mouth, and sorry for the late reply.

Hi, @h-k8888  Any new progress about the code?

**Comment by Rocense** [comment]
Hi, @h-k8888 Any new progress about the code?

**Comment by KkCabin** [comment]
Hi, @h-k8888 Any new progress about the code?

**Comment by h-k8888** [comment]
Our code is under refactoring. 
And our code will be released along with our recent work LOG-LIO2 in a few days.

**Comment by chengwei0427** [comment]
Glad to hear that. And look forward to your new work.

**Comment by h-k8888** [comment]
Thanks for the interest in our work, the code is open-source.
And our recent work LOG-LIO2 is coming soon!
