### ISSUE TITLE
how to make it compatible for Velodyne 16 line

### ISSUE THREAD

**Issue by CharlieV5** [tiev-tongji/LOG-LIO#4]
Hi! Thank you for your open source code! 
I notice that the code is adaptive for VLP-32 and Ouster. How to make it compatible for Velodyne 16 line?

**Comment by h-k8888** [comment]
Hi, thanks for the interest.
Adapting to a specific LiDAR, you need to follow [RingFALS Normal Estimator](https://github.com/tiev-tongji/RingFalsNormal) and build the lookup table first.
All the parameters for the LiDAR need to be set carefully.
And I suggest you to check whether the normal estimation is correct with RingFALS visualisation first.
