### ISSUE TITLE
How can planarity threshold be larger than 1?

### ISSUE THREAD

**Issue by brytsknguyen** [tiev-tongji/LOG-LIO#5]
Hi friends,

Thanks for the great work. I notice that in the paper as well as the code you set the minimum planarity threshold to be 1.0. Ne shi bu ke neng. Theorectically it can only be from 0 to 1 right?

![image](https://github.com/tiev-tongji/LOG-LIO/assets/13504903/6525a94e-18c5-4e0e-bd36-db8ad30df0af)

**Comment by h-k8888** [comment]
@brytsknguyen 
Thanks for your interest.  Many of our ideas are inspired by your work.
The default value in the laserMapping.cpp is set to 1.0.
In the yaml file, we set the value to 0.6.
It's a mistake in our paper that defines planarity greater than 1.0.

**Comment by brytsknguyen** [comment]
noted with thanks!
